- name: login gcloud new create service account
  command: >
    gcloud auth activate-service-account
    --key-file={{ gcp_existing_key }}
  register: auth_result
  failed_when: auth_result.rc != 0

- name: Set gcloud default project
  command: >
    gcloud config set project {{ gcp_project_id }}
  register: project_result
