# GCP
gcp_project_id: "k8stest-478013"
gcp_sa_name: "ghac-deployer2"
gcp_sa_display_name: "ghac-deployer2"
gcp_existing_key: ""
gcp_gen_key: ""

# GitHub
github_owner: "davidtestdocker"
github_repo: "ansiblek8s"
github_secret_name: "GKE_SA_KEY"

